### ISSUE TITLE
preload 逻辑无效

### ISSUE THREAD

**Issue by Senorsen** [GyrosWorkshop/Wukong#2]
preload地址：
![image](https://cloud.githubusercontent.com/assets/4176091/17013838/7992028a-4f53-11e6-8af3-92f1a7e1c246.png)

播放时：
![image](https://cloud.githubusercontent.com/assets/4176091/17013845/820d144a-4f53-11e6-8669-19611770e7a3.png)

地址不一致，所以客户端缓存逻辑无效。

建议：后端维持一定时间的地址，给所有客户端提供相同地址。

**Comment by richard1122** [comment]
没懂，这个应该需要provider保持一致性。

**Comment by Senorsen** [comment]
我是指：可否考虑，后端在客户端updateNextSong时，就获取一次播放地址，之后都使用这个临时保存下的播放地址。

**Comment by Senorsen** [comment]
即：在此处就进行歌曲地址的获取

https://github.com/GyrosWorkshop/Wukong/blob/34866a0bfa32a2212a2fd65c5a61f3a3ec4efb64/src/Wukong/Controllers/ChannelController.cs#L50

**Comment by Senorsen** [comment]
而不是在向客户端发送 Play 及 NextSongUpdate 时才获取

https://github.com/GyrosWorkshop/Wukong/blob/34866a0bfa32a2212a2fd65c5a61f3a3ec4efb64/src/Wukong/Services/Channel.cs#L294

**Comment by richard1122** [comment]
不能这样做的，现在这样延后获取地址是专门设计的。 
之前qq音乐在人多的时候，会发生轮到你时候音乐地址已经超时了。所以才改成了保证在播放前获取地址。

**Comment by richard1122** [comment]
哦，我明白你的意思了。应该改成在服务器发送NextSong和发送Play时候是一个地址。
