### ISSUE TITLE
前后端心跳时使用统一的格式

### ISSUE THREAD

**Issue by richard1122** [GyrosWorkshop/Wukong#35]
与原有事件格式一致：
![image](https://cloud.githubusercontent.com/assets/2534277/23896391/38d5df28-08e4-11e7-9ee5-af1a7131cfe7.png)

**Comment by Qusic** [comment]
最好都用json吧
现在前端不得不特判一下不太方便

**Comment by Qusic** [comment]
```
{
  eventName: "ping",
  timestamp: (number)
}
```
这样？
现在pong并不是收到ping的时候发的，而是前端定时发的，不如都叫ping了

**Comment by richard1122** [comment]
@Qusic 都叫 ping 好了，另外我觉得不需要 timestamp 的？

**Comment by Qusic** [comment]
timestamp一开始森森加的，那不要也可以

**Comment by richard1122** [comment]
据说现在不用心跳了
