### ISSUE TITLE
乱发play播放混乱问题

### ISSUE THREAD

**Issue by Senorsen** [GyrosWorkshop/Wukong#4]
## 现象

在播放歌曲b后，一段时间内（约十几秒）中间突然开始播放歌曲a。但按照正常安排，应该播放歌曲b。

且服务器端保存的正在播放仍然是歌曲b：在歌曲a播放进行中，downvote、finish均返回400；刷新后会再次回到正确的播放歌曲b。
## 可能的复现步骤
1. 单独进入一个无人问津的频道test
2. 在开始播放用户歌单的第一首歌曲a时，点击切歌

此时开始播放歌曲b，有可能在一段时间后重新播放歌曲a。

<hr>

**Update:** 出现问题前，有使用过 downvote

**Comment by richard1122** [comment]
似乎知道是啥原因了

**Comment by Senorsen** [comment]
再次遇到此问题，疑似没有被解决

**Comment by Senorsen** [comment]
疑与早期 provider 随机响应迟滞有关，现在问题已自行消失。

**Comment by aoli-al** [comment]
似乎又有人遇到了这个问题

**Comment by Senorsen** [comment]
增加了 Provider 的稳定性，暂时绕过问题
