### ISSUE TITLE
同一账号在其它地方登录时没有断开 ws 链接

### ISSUE THREAD

**Issue by richard1122** [GyrosWorkshop/Wukong#50]

**Comment by aoli-al** [comment]
我看了一下后端代码好像是会断开链接的。。。

**Comment by richard1122** [comment]
我咋没找到这段代码。。。。
https://github.com/GyrosWorkshop/Wukong/blob/master/Wukong/Services/Socket.cs

**Comment by aoli-al** [comment]
@richard1122 https://github.com/GyrosWorkshop/Wukong/blob/master/Wukong/Services/Socket.cs#L70

**Comment by richard1122** [comment]
@Leeleo3x 有道理！

**Comment by richard1122** [comment]
@Leeleo3x close issue

**Comment by richard1122** [comment]
@richard1122 close
