### ISSUE TITLE
Use SignalIR to replace Websocket

### ISSUE THREAD

**Issue by aoli-al** [GyrosWorkshop/Wukong#64]
Due to the limitation of concurrent connection numbers we are going to replace Websocket with SignalIR.

**Comment by Senorsen** [comment]
@Leeleo3x

**Comment by Qusic** [comment]
https://github.com/SignalR/bower-signalr
js client居然是jquery插件。。还是别用这个了吧

**Comment by richard1122** [comment]
https://github.com/aspnet/SignalR/blob/dev/client-ts/Microsoft.AspNetCore.SignalR.Client.TS/Transports.ts#L18
signalR 的Transport 中包含 websocket 实现，看起来没法绕开。

**Comment by richard1122** [comment]
@Qusic 这个纯净实现似乎是不依赖任何的
https://github.com/aspnet/SignalR/tree/dev/client-ts

**Comment by richard1122** [comment]
@Qusic 你发的那个是 asp.net 的

**Comment by richard1122** [comment]
This is not an issue any more.
