### ISSUE TITLE
播放顺序的问题

### ISSUE THREAD

**Issue by Qusic** [GyrosWorkshop/Wukong#65]
后端应该是依次播放每个用户的列表里的的第一首
~~然后前端在自己的一首歌被播了的时候把这首放到列表最后，再把歌单传给后端~~
客户端不再发songs事件，sync的时候带上第一首歌

后端发的play事件得加上一个user字段告诉前端这是谁列表里的歌

**Comment by Leeleo3x** [comment]
Fixed.
