### ISSUE TITLE
提议一个S->C的play的微小的改动

### ISSUE THREAD

**Issue by Qusic** [GyrosWorkshop/Wukong#96]
把发送elapsed改成发送这首歌开始播放的时间戳
一方面是这样消除了网络延迟造成的播放进度在客户端之间微小的不同步的问题
另外是因为手机上第一次收到play和真正开始播放之间要等待用户输入，这样才方便计算开始播放的进度

**Comment by richard1122** [comment]
@Qusic 以后需要每一首开始前都要点一下吗？

**Comment by Qusic** [comment]
前端处理了。。
